spring.application.name=api-rosatel

# Configuración Cloudinary
cloudinary.cloud_name=dwuotua9m
cloudinary.api_key=711161526257484
cloudinary.api_secret=bfcJfBnF5M7OGzednS32gCPt_vM
# Configuración de subida de archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
